name: reduct
description: An elementary yet adaptable state management solution for Dart.
version: 1.0.1
repository: https://github.com/Eronildo/reduct

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
